name: flutter_parse_server
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  parse_server_sdk: ^2.0.1
  flutter_dotenv: ^2.1.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.4
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
